### ISSUE TITLE
How did you install "x86_64-elf-4.9.0-Linux-x86_64"

### ISSUE THREAD

**Issue by sinkarharshad** [runtimejs/toolchain-bin-linux#1]
Can you please guide me how you installed this package?

Thank you in advance!

**Comment by iefserge** [comment]
@sinkarharshad no need to install this one, unpack it to any directory and (optional) add `/bin` directory to paths.

**Comment by sinkarharshad** [comment]
When I am trying to compile a simple hello world program, I am getting this error :!
My Code:

#include <stdio.h>
#include <unistd.h>

int main(int argc, char** argv) {
 
	for (int i=0; i<=5; i++){
	
		printf("Hello, World\n");
		sleep (2);
	}
}


Error:

$ ./x86_64-elf-gcc /hellow/hellow.c
/c:5:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.

whats the problem here? 
thank you.

**Comment by iefserge** [comment]
This toolchain does not target Linux, but a standalone x86_64 platforms. For compiling Linux programs you can use your distro's package manager to install GCC.

**Comment by sinkarharshad** [comment]
I want to create an executable for  x86_64 target machine (cross-compiling). Thats why I was trying the same. Can you please guide how I can achieve this?

**Comment by iefserge** [comment]
Standard headers and platform functions (printf/sleep) are OS-dependent and aren't available the in standalone toolchain. This works for baremetal programming.
